### ISSUE TITLE
请问这个 API_KEY_INVALID 是什么原因呢？已经填写刚申请的Gemini key 了

### ISSUE THREAD

**Issue by zyc63959** [Jazee6/cloudflare-ai-web#13]
[nuxt] [request error] [unhandled] [500] [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] API key not valid. Please pass a valid API key. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}}]
  at (index.mjs:1:117486)  
  at (index.mjs:1:121869)

**Comment by panxiaoguang** [comment]
你是在谷歌申请的吗？
