### ISSUE TITLE
为什么不回复信息，google key 也申请了，

### ISSUE THREAD

**Issue by hieivip** [Jazee6/cloudflare-ai-web#16]
为什么不回复信息，google key 也申请了，
![image](https://github.com/Jazee6/cloudflare-ai-web/assets/54146330/563f6e0c-6506-4a28-8379-b1a71bc30aad)

**Comment by Jazee6** [comment]
检查服务端日志

**Comment by hieivip** [comment]
Error: [GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY

这个是说我的google api 有问题嘛/

**Comment by Jazee6** [comment]
回复有敏感内容，被屏蔽了。建议重新创建对话试一下
