### ISSUE TITLE
gemini 报错 500

### ISSUE THREAD

**Issue by ywhnghng** [Jazee6/cloudflare-ai-web#17]
gemini 报错 500，其他模型使用正常

**Comment by Jazee6** [comment]
请检查后台日志

**Comment by ywhnghng** [comment]
[nuxt] [request error] [unhandled] [500] [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] API key not valid. Please pass a valid API key. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}}]
  at (index.mjs:1:117527)  
  at (index.mjs:1:121910)

**Comment by Jazee6** [comment]
API key无效
