### ISSUE TITLE
所有问题，都是返回500

### ISSUE THREAD

**Issue by xiaopaul** [Jazee6/cloudflare-ai-web#20]
您好，请问这是什么原因？
一键部署在Vercel上，界面正常，没有用其他API，只是Gremini. 谢谢。

![image](https://github.com/Jazee6/cloudflare-ai-web/assets/99534058/44e5b82c-ba14-4ea3-bdeb-9c7fdb62e81d)

**Comment by Jazee6** [comment]
请检查后台日志

**Comment by xiaopaul** [comment]
这是没有正确获得Token吗？还是必须要获取Google APi？因为我一开始没打算用Google的api，所以G_api_key和URL都没有填。
[POST] /api/auth/gemini/?model=gemini-pro status=500

[nuxt] [request error] [unhandled] [500] [GoogleGenerativeAI Error]: Error fetching from 
![image](https://github.com/Jazee6/cloudflare-ai-web/assets/99534058/58deb336-3549-4646-a7d7-522ffa07fec6)


https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] API key not valid. Please pass a valid API key. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}}]
  at (index.mjs:1:117527)  
  at (index.mjs:1:121910)

**Comment by xiaopaul** [comment]
搞定了，非常感谢。。
