### ISSUE TITLE
[Bug] GeminiPro Vision

### ISSUE THREAD

**Issue by muxinxy** [Jazee6/cloudflare-ai-web#21]
GeminiPro Vision 对于中文问题无响应，而且同一个对话不能上传第二张图片。

![image](https://github.com/Jazee6/cloudflare-ai-web/assets/32673109/6843bc61-0d03-4623-93cc-6cde026a2ddc)

**Comment by Jazee6** [comment]
请检查控制台或后台日志

**Comment by muxinxy** [comment]
中文问题有回答了，就是不太稳定，偶尔没反应。有时候不能上传图片，刷新网页可以解决。控制台和后台日志没有异常信息。
```
[POST] /api/auth/gemini/?model=gemini-pro-vision status=200
[GET] /api/pass status=200
```
