### ISSUE TITLE
演示网站画图不可用

### ISSUE THREAD

**Issue by woshichenghaibo** [Jazee6/cloudflare-ai-web#23]
图功能不可用，一直有一个小黑点儿，在转圈

**Comment by Jazee6** [comment]
收到，排查中

**Comment by myli0724** [comment]
> 收到，排查中

大概是什么原因，我好像自己用官方接口试了也是错误

**Comment by myli0724** [comment]
> > > 收到，排查中
> > 
> > 
> > 大概是什么原因，我好像自己用官方接口试了也是错误
> 
> 目前看是cloudflare内部的错误

果然是这样，那有向cf反馈了吗😂

**Comment by Jazee6** [comment]
> > > > 收到，排查中
> > > 
> > > 
> > > 大概是什么原因，我好像自己用官方接口试了也是错误
> > 
> > 
> > 目前看是cloudflare内部的错误
> 
> 果然是这样，那有向cf反馈了吗😂

社区已经有类似反馈

**Comment by myli0724** [comment]
> > > > > 收到，排查中
> > > > 
> > > > 
> > > > 大概是什么原因，我好像自己用官方接口试了也是错误
> > > 
> > > 
> > > 目前看是cloudflare内部的错误
> > 
> > 
> > 果然是这样，那有向cf反馈了吗😂
> 
> 社区已经有类似反馈

官方文档还没更新，接口修改了，需要提交以下参数：payload = {'prompt': 'cyberpunk cat',
           'num_steps': 20
           }，添加个num_steps 20即可
