### ISSUE TITLE
为什么我的输入对话框位置不在底部？

### ISSUE THREAD

**Issue by juneix** [Jazee6/cloudflare-ai-web#26]
如图，我的输入框位置跑到中央去了，试过强制刷新、隐私模式还是一样
![iShot_2024-03-21_14 28 25](https://github.com/Jazee6/cloudflare-ai-web/assets/81808039/c0031f40-4c5e-456b-8540-3fcc0a975590)

另外我对比了一下，使用 vercel 随机分配的域名显示正常的，底部也有版本信息。绑定自定义域名（托管在 cf）就显示不正常了
![iShot_2024-03-21_14 34 19](https://github.com/Jazee6/cloudflare-ai-web/assets/81808039/c6c6abb9-a1fd-4fb9-8b2e-067d3d29c0e6)

**Comment by Jazee6** [comment]
请说明一下浏览器版本，操作系统信息

**Comment by Jazee6** [comment]
2.0beta已推出，请检查是否解决问题(●'◡'●)

**Comment by juneix** [comment]
> 2.0beta已推出，请检查是否解决问题(●'◡'●)

已经正常了。感谢大佬🙏
