### ISSUE TITLE
希望增加gemini-1.5-pro-latest模型

### ISSUE THREAD

**Issue by juneix** [Jazee6/cloudflare-ai-web#30]
默认的 gemini pro 不知道是啥版本，很笨，不太好用。最近谷歌已经开放gemini-1.5-pro的 api 申请了，我两个谷歌账号都申请成功了，应该还比较容易。希望可以增加`gemini-1.5-pro-latest`模型。

Gemini 1.5 Pro Waitlist申请地址
https://aistudio.google.com/app/waitlist/97445851

附上谷歌回复的邮件参考，调用地址是`/v1beta`，模型名是`gemini-1.5-pro-latest`

> Gemini 1.5 Pro API
You should now have API access to Gemini 1.5 Pro on the GCP project you shared with us!
To get started:
[Create an API key](https://aistudio.google.com/app/apikey?utm_source=newsletter&utm_medium=email&utm_campaign=1.5p-api-launch_march&utm_content=) generated from your allowlisted GCP Project.
Run the [list_models Python method](https://ai.google.dev/api/python/google/generativeai/list_models) or this cURL command:
curl 'https://generativelanguage.googleapis.com/v1beta/models?key=<YOUR_API_KEY>'
Check out our [Gemini API cookbook](https://github.com/google-gemini/gemini-api-cookbook/tree/main) or visit the [Gemini API docs](https://ai.google.dev/docs/gemini_api_overview), open up the [Python quickstart](https://ai.google.dev/tutorials/python_quickstart) (or the [programming language of your choice](https://ai.google.dev/tutorials)) and update code by replacing the model name with 'gemini-1.5-pro-latest'.
Having access issues? Go to https://aistudio.google.com/app/apikey and confirm that the API key you are using is tied to your allowlisted Google Cloud Project.

**Comment by Jazee6** [comment]
你可以fork本项目，在`utils/db.ts`中增加此模型，并在`server/api/gemini.post.ts`中修改为以下代码

`const m = genAI.getGenerativeModel({model, safetySettings}, {apiVersion: 'v1beta'})`
