### ISSUE TITLE
可以支持chatgpt3.5 turbo直接使用吗

### ISSUE THREAD

**Issue by yuanlai9** [Jazee6/cloudflare-ai-web#31]

**Comment by zjavax** [comment]
等大佬一波更新,应该快了.  就怕openia那边不给用了

**Comment by brooklynb7** [comment]
rate limit exceeded

**Comment by Jazee6** [comment]
没有理解你的意思

**Comment by zjavax** [comment]
> 没有理解你的意思

看网上的介绍,openai免登录之后, api key可以随便填写就可以使用
https://twitter.com/geekbb/status/1775368703934341579

**Comment by Jazee6** [comment]
> > 没有理解你的意思
> 
> 看网上的介绍,openai免登录之后, api key可以随便填写就可以使用 https://twitter.com/geekbb/status/1775368703934341579

了解了，会考虑支持
