### ISSUE TITLE
页面无法输入密码

### ISSUE THREAD

**Issue by honeyshine75** [Jazee6/cloudflare-ai-web#32]
设置密码后，页面并未弹出登录框，希望增加登录框

**Comment by tomleung1996** [comment]
+1，请问问题解决了么

**Comment by hsoong** [comment]
设置密码操作可以在浏览器的console中输入`localStorage.setItem('access_pass', 'YOUR PASSWORD')`命令来实现。

**Comment by honeyshine75** [comment]
考虑增加一个弹窗输入吗？

**Comment by Jazee6** [comment]
感谢反馈，正在排查问题

**Comment by Jazee6** [comment]
当前的触发模式为发送消息后触发弹框，后续考虑其他方式

**Comment by Auction99** [comment]
并未弹窗，而是返回401
