### ISSUE TITLE
反代配置问题

### ISSUE THREAD

**Issue by snake-git** [Jazee6/cloudflare-ai-web#36]
安照大佬项目的指引，基本搭建成功，能跑起来了。目前唯一的问题是gemini pro 出现地区不支持问题，大佬项目里说到：
或者在nuxt.config.ts中添加以下配置

nitro: {
    vercel: {
        regions: ["cle1", "iad1", "pdx1", "sfo1", "sin1", "syd1", "hnd1", "kix1"]
    }
}

本人小白，找了半天不知道在哪里添加这个内容，麻烦大佬再具体指导一下（如果能截图说明更好），谢谢！

**Comment by hsoong** [comment]
`nuxt.config.ts`就在工程的根目录下。

**Comment by snake-git** [comment]
> `nuxt.config.ts`就在工程的根目录下。
谢谢大佬回复。是直接在我fork的分支里面改吗？

**Comment by Jazee6** [comment]
> Author

是的

**Comment by Jazee6** [comment]
> > `nuxt.config.ts`就在工程的根目录下。
> > 谢谢大佬回复。是直接在我fork的分支里面改吗？

是的
