### ISSUE TITLE
求教大佬们，在哪里添加自己的openai和gemini的api key?

### ISSUE THREAD

**Issue by xdl2015** [Jazee6/cloudflare-ai-web#37]
在对话页面的设置按钮中只有填写openai api key的选项，但是填写后依然无法使用chatgpt，gemini的api连填写的地方都没有，实在不知道怎么办？只好向大佬们求助，谢谢解答

**Comment by snake-git** [comment]
> 在对话页面的设置按钮中只有填写openai api key的选项，但是填写后依然无法使用chatgpt，gemini的api连填写的地方都没有，实在不知道怎么办？只好向大佬们求助，谢谢解答

按照大佬的教程填写：
![0000](https://github.com/Jazee6/cloudflare-ai-web/assets/20527089/3959d7d7-1956-41d5-8f43-11e69ff6cb22)

**Comment by snake-git** [comment]
在你部署的 Vercel.com 里面的环境变量填：https://vercel.com/

**Comment by xdl2015** [comment]
> 在你部署的 Vercel.com 里面的环境变量填：https://vercel.com/

500 {"url":"/api/gemini","statusCode":500,"statusMessage":"","message":"[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] API key not valid. Please pass a valid API key. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"API_KEY_INVALID\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\"}}]","stack":""}
![screencapture-verce](https://github.com/Jazee6/cloudflare-ai-web/assets/132360670/8ac0f9da-a089-4661-9d1b-f722d5415c5e)

**Comment by snake-git** [comment]
> > 在你部署的 Vercel.com 里面的环境变量填：https://vercel.com/  我是这样设置的 但是聊天页面返回这段错误提示，大佬能指点一下是什么原因吗？
> 
> 500 {"url":"/api/gemini","statusCode":500,"statusMessage":"","message":"[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] API key not valid. Please pass a valid API key. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}}]","stack":""} ![screencapture-verce](https://private-user-images.githubusercontent.com/132360670/320093449-8ac0f9da-a089-4661-9d1b-f722d5415c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzc4NTksIm5iZiI6MTcxMjM3NzU1OSwicGF0aCI6Ii8xMzIzNjA2NzAvMzIwMDkzNDQ5LThhYzBmOWRhLWEwODktNDY2MS05ZDFiLWY3MjJkNTQxNWM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwNDI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTdkNWUyOTM4NzVjMGYxMzcxMzUzMmNkYzdkNmM5YWI4MjY3Zjg4Y2E4OTNmYjY1MTNkOTUyZGE1NDFjOGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AkwEWSz38pposjEDUH9VXqk0pngw5iSzNB7asBGlXgo)

错误提示是你的gemini  key 失效了。去重新申请个试试。

**Comment by xdl2015** [comment]
我可是刚申请的Gemini 的API key 有点懵了……

**Comment by xdl2015** [comment]
> > > 在你部署的 Vercel.com 里面的环境变量填：https://vercel.com/  我是这样设置的 但是聊天页面返回这段错误提示，大佬能指点一下是什么原因吗？
> 
> > 
> 
> > 500 {"url":"/api/gemini","statusCode":500,"statusMessage":"","message":"[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:streamGenerateContent?alt=sse: [400 Bad Request] API key not valid. Please pass a valid API key. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}}]","stack":""} ![screencapture-verce](https://private-user-images.githubusercontent.com/132360670/320093449-8ac0f9da-a089-4661-9d1b-f722d5415c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzc4NTksIm5iZiI6MTcxMjM3NzU1OSwicGF0aCI6Ii8xMzIzNjA2NzAvMzIwMDkzNDQ5LThhYzBmOWRhLWEwODktNDY2MS05ZDFiLWY3MjJkNTQxNWM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwNDI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTdkNWUyOTM4NzVjMGYxMzcxMzUzMmNkYzdkNmM5YWI4MjY3Zjg4Y2E4OTNmYjY1MTNkOTUyZGE1NDFjOGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AkwEWSz38pposjEDUH9VXqk0pngw5iSzNB7asBGlXgo)
> 
> 
> 
> 错误提示是你的gemini  key 失效了。去重新申请个试试。

我可是刚申请的Gemini 的API key 有点懵了……
