### ISSUE TITLE
部署后无法访问

### ISSUE THREAD

**Issue by Xuezenghuigithub** [Jazee6/cloudflare-ai-web#4]
<img width="1380" alt="image" src="https://github.com/Jazee6/cloudflare-ai-web/assets/40421053/847f6658-ff6a-4fbf-b9a6-922c8b3a27f4">

**Comment by Jazee6** [comment]
你好，请检查`OPENAI_API_KEY`环境变量是否配置正确，以及key的有效性

**Comment by Xuezenghuigithub** [comment]
<img width="1183" alt="image" src="https://github.com/Jazee6/cloudflare-ai-web/assets/40421053/cbcba94f-0672-4f54-9c55-e9ae6276946f">

有配置，并且我重新 Redeploy 了应用，Gemini 是可用的。

站点：https://ai.zander.fun

**Comment by Jazee6** [comment]
vercel - Logs 检查错误信息

**Comment by Xuezenghuigithub** [comment]
是我 api key 的问题，谢谢

**Comment by QiuQiu20001** [comment]
求教，我用的GEMINI，弹错提示API KEY无效，是不是文档里的变量名不对呀？？KEY是没啥问题的，我刚生成的新的。
![Uploading 01.png…]()
