### ISSUE TITLE
如果在cloudflare pages中部署，G_API_URL应该如何配置

### ISSUE THREAD

**Issue by jhyvictory** [Jazee6/cloudflare-ai-web#46]
或者在nuxt.config.ts中添加以下配置
‵‵‵
nitro: {
    vercel: {
        regions: ["cle1", "iad1", "pdx1", "sfo1", "sin1", "syd1", "hnd1", "kix1"]
    }
}
‵‵‵
以上应该如何修改

**Comment by Jazee6** [comment]
fork后修改
