### ISSUE TITLE
部署完成但报错了。

### ISSUE THREAD

**Issue by gallexy** [Jazee6/cloudflare-ai-web#49]
<style>body{margin:0;padding:0}</style>  <script> if (!navigator.cookieEnabled) { window.addEventListener('DOMContentLoaded', function () { var cookieEl = document.getElementById('cookie-alert'); cookieEl.style.display = 'block'; }) } </script>  </head> <body> <div id="cf-wrapper"> <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div> <div id="cf-error-details" class="cf-error-details-wrapper"> <div class="cf-wrapper cf-header cf-error-overview"> <h1> <span class="cf-error-type" data-translate="error">Error</span> <span class="cf-error-code">1101</span> <small class="heading-ray-id">Ray ID: 8885b5d9562815fb &bull; 2024-05-23 14:24:34 UTC</small> </h1> <h2 class="cf-subheadline" data-translate="error_desc">Worker threw exception</h2> </div> <section></section> <div class="cf-section cf-wrapper"> <div class="cf-columns two"> <div class="cf-column"> <h2 data-translate="what_happened">What happened?</h2> <p>You've requested a page on a website (gateway.ai.cloudflare.com) that is on the <a href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> network. An unknown error occurred while rendering the page.</p> </div> <div class="cf-column"> <h2 data-translate="what_can_i_do">What can I do?</h2> <p><strong>If you are the owner of this website:</strong><br />you should <a href="https://www.cloudflare.com/login?utm_source=error_100x" target="_blank">login to Cloudflare</a> and check the error logs for gateway.ai.cloudflare.com.</p> </div> </div> </div> <div class="cf-error-footer cf-wrapper w
![屏幕截图 2024-05-23 222712](https://github.com/Jazee6/cloudflare-ai-web/assets/3725145/2385a611-2e4d-4334-a0db-baa7c164b669)

**Comment by AQLI21** [comment]
我的也是
目前上面只有Gemini能用，Cloudflare AI全报错1101

**Comment by Jazee6** [comment]
> 我的也是 目前上面只有Gemini能用，Cloudflare AI全报错1101

能否提供详细的报错信息

**Comment by AQLI21** [comment]
500类的报错，似乎是CF AI Getway Universal API的问题，在CF控制面板上直接访问我的API同样报错1101。
部署中使用Cloudflare AI的模型会报错Cloudflare1101错误的整个HTML。
同时我在CF控制面板也没有任何有关请求或Error的数据或日志。在CF的discord里留了言。。

**Comment by Jazee6** [comment]
> 500类的报错，似乎是CF AI Getway Universal API的问题，在CF控制面板上直接访问我的API同样报错1101。 部署中使用Cloudflare AI的模型会报错Cloudflare1101错误的整个HTML。 同时我在CF控制面板也没有任何有关请求或Error的数据或日志。在CF的discord里留了言。。

部署在什么平台呢

**Comment by AQLI21** [comment]
Vercel上按照大佬的Readme部署的

**Comment by gallexy** [comment]
我cloudflare上部署成了 .
![image](https://github.com/Jazee6/cloudflare-ai-web/assets/3725145/eec7a9e1-ba19-40c4-babf-29e58aaf1661)

**Comment by AQLI21** [comment]
刚刚研究了一下，原因似乎是因我的部署名称和Cloudflare AI Gateway 的API 采用了相同的名称导致的... 改了之后没问题了

**Comment by gallexy** [comment]
试了一下vercel也能成功，CF_TOKEN和CF_GATEWAY一定要设对， CF_GATEWAY是 https://gateway.ai.cloudflare.com/v1/8e26xxxxxxxxxxxxxxxxxxxxxxxxx/{GATEWAYID}
