### ISSUE TITLE
按照您的操作也不行呢，需要到对应的官网获取key

### ISSUE THREAD

**Issue by qingwz1994** [Jazee6/cloudflare-ai-web#5]
Error: recieved non-200 status code, {"status":401,"statusText":"Unauthorized","body":"{\n    \"error\": {\n        \"message\": \"Incorrect API key provided: undefined. You can find your API key at https://platform.openai.com/account/api-keys.\",\n        \"type\": \"invalid_request_error\",\n        \"param\": null,\n        \"code\": \"invalid_api_key\"\n    }\n}\n"}

**Comment by Jazee6** [comment]
是的，ChatGPT需要key才能使用

**Comment by QiuQiu20001** [comment]
我部署了GEMINI，也获取了KEY添加到变量了，但是不会回话，好难哦

**Comment by Jazee6** [comment]
请确认`G_API_URL`反代设置正确

**Comment by Jazee6** [comment]
> 我部署了GEMINI，也获取了KEY添加到变量了，但是不会回话，好难哦

请确认`G_API_URL`反代设置正确
