### ISSUE TITLE
能否不使用cf的aigateway而通过其它第三方gpt的api

### ISSUE THREAD

**Issue by Huchangzhi** [Jazee6/cloudflare-ai-web#59]
能否不使用cf的aigateway而通过其它第三方gpt的api，如[https://github.com/popjane/free_chatgpt_api](https://github.com/popjane/free_chatgpt_api)建议添加一个使用非官方api的选项，openai的api太难注册了

**Comment by Jazee6** [comment]
值得考虑，预计下个版本更新

**Comment by Huchangzhi** [comment]
能不能先给个解决方法
