### ISSUE TITLE
请问openai的key使用one-api的是否可以，另外one-api的接口地址变量是openai_api_url吗?

### ISSUE THREAD

**Issue by lizhe0326** [Jazee6/cloudflare-ai-web#7]
OPENAI_API_KEY添加了one-api的key。增加了一个OPENAI_API_URL填写了one-api的代理地址，但是chatgpt-3.5没有回应。
使用vercel搭建。是否只能使用官方key

Error: recieved non-200 status code, {"status":401,"statusText":"Unauthorized","body":"{\n    \"error\": {\n        \"message\": \"Incorrect API key provided: sk-TK6NM***************************************48B5. You can find your API key at https://platform.openai.com/account/api-keys.\",\n        \"type\": \"invalid_request_error\",\n        \"param\": null,\n        \"code\": \"invalid_api_key\"\n    }\n}\n"}

**Comment by Jazee6** [comment]
你好，只能使用官方key，走的是cloudflare ai gateway的代理

**Comment by lizhe0326** [comment]
好的，感谢回复
