### ISSUE TITLE
有计划支持chatgpt其他语言模型吗，如GPT4

### ISSUE THREAD

**Issue by coppea** [Jazee6/cloudflare-ai-web#8]

**Comment by Jazee6** [comment]
暂时没有计划，因为我没有能测试的Key🥲

**Comment by panxiaoguang** [comment]
> 暂时没有计划，因为没有能测试的Key🥲

可以把chatgpt的请求地址改成用户添加自定义环境变量吗？毕竟官方的key太贵了而且条件也比较苛刻，相反国内有很多one-api代理的key, gpt-4也是合理的价格。这样测试起来也方便。

**Comment by Jazee6** [comment]
> > 暂时没有计划，因为没有能测试的Key🥲
> 
> 可以把chatgpt的请求地址改成用户添加自定义环境变量吗？毕竟官方的key太贵了而且条件也比较苛刻，相反国内有很多one-api代理的key, gpt-4也是合理的价格。这样测试起来也方便。

类似的项目有很多，我们会评估一下可行性

**Comment by fxcl** [comment]
可以添加月之暗面么?
https://platform.moonshot.cn/docs

**Comment by Jazee6** [comment]
你可以fork本项目，在`utils/db.ts`中增加此模型
